apiVersion: v1
kind: List
items:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: prometheus-k8s-admission-create
      namespace: monitoring
      labels:
        app: kube-prometheus-stack-admission-create
        app.kubernetes.io/component: prometheus-operator-webhook
        app.kubernetes.io/instance: prometheus
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: "56.6.2"
        chart: kube-prometheus-stack-56.6.2
        heritage: Helm
        release: prometheus
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    spec:
      backoffLimit: 6
      completions: 1
      parallelism: 1
      template:
        metadata:
          labels:
            app: kube-prometheus-stack-admission-create
            app.kubernetes.io/component: prometheus-operator-webhook
            app.kubernetes.io/instance: prometheus
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
            app.kubernetes.io/part-of: kube-prometheus-stack
            app.kubernetes.io/version: "56.6.2"
            chart: kube-prometheus-stack-56.6.2
            heritage: Helm
            release: prometheus
        spec:
          serviceAccountName: prometheus-k8s-admission
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: create
              image: registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20221220-controller-v1.5.1-58-g787ea74b6
              imagePullPolicy: IfNotPresent
              args:
                - create
                - --host=prometheus-k8s-operator,prometheus-k8s-operator.monitoring.svc
                - --namespace=monitoring
                - --secret-name=prometheus-k8s-admission
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true

  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: prometheus-k8s-admission-patch
      namespace: monitoring
      labels:
        app: kube-prometheus-stack-admission-patch
        app.kubernetes.io/component: prometheus-operator-webhook
        app.kubernetes.io/instance: prometheus
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: "56.6.2"
        chart: kube-prometheus-stack-56.6.2
        heritage: Helm
        release: prometheus
      annotations:
        helm.sh/hook: post-install,post-upgrade
        helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    spec:
      backoffLimit: 6
      completions: 1
      parallelism: 1
      template:
        metadata:
          labels:
            app: kube-prometheus-stack-admission-patch
            app.kubernetes.io/component: prometheus-operator-webhook
            app.kubernetes.io/instance: prometheus
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
            app.kubernetes.io/part-of: kube-prometheus-stack
            app.kubernetes.io/version: "56.6.2"
            chart: kube-prometheus-stack-56.6.2
            heritage: Helm
            release: prometheus
        spec:
          serviceAccountName: prometheus-k8s-admission
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: patch
              image: registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20221220-controller-v1.5.1-58-g787ea74b6
              imagePullPolicy: IfNotPresent
              args:
                - patch
                - --webhook-name=prometheus-k8s-admission
                - --namespace=monitoring
                - --secret-name=prometheus-k8s-admission
                - --patch-failure-policy=
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
