apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: prometheus-grafana
      namespace: monitoring
      labels:
        app.kubernetes.io/instance: prometheus
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: grafana
        app.kubernetes.io/version: "9.2.0"
        helm.sh/chart: grafana-7.3.0
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: standard
      volumeMode: Filesystem

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: prometheus-prometheus-k8s-prometheus-db-prometheus-prometheus-k8s-prometheus-0
      namespace: monitoring
      labels:
        app.kubernetes.io/instance: prometheus-k8s-prometheus
        app.kubernetes.io/managed-by: prometheus-operator
        app.kubernetes.io/name: prometheus
        operator.prometheus.io/name: prometheus-k8s-prometheus
        operator.prometheus.io/shard: "0"
        prometheus: prometheus-k8s-prometheus
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5G
      storageClassName: standard
      volumeMode: Filesystem
