apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: kind-worker2
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-02-21T06:09:37Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/instance: prometheus
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: grafana
      app.kubernetes.io/version: 9.2.0
      helm.sh/chart: grafana-7.3.0
    name: prometheus-grafana
    namespace: monitoring
    resourceVersion: "3399"
    uid: b65bfd73-107b-4885-ac27-130e6e869215
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: standard
    volumeMode: Filesystem
    volumeName: pvc-b65bfd73-107b-4885-ac27-130e6e869215
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: kind-worker2
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-02-21T06:10:21Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/instance: prometheus-k8s-prometheus
      app.kubernetes.io/managed-by: prometheus-operator
      app.kubernetes.io/name: prometheus
      operator.prometheus.io/name: prometheus-k8s-prometheus
      operator.prometheus.io/shard: "0"
      prometheus: prometheus-k8s-prometheus
    name: prometheus-prometheus-k8s-prometheus-db-prometheus-prometheus-k8s-prometheus-0
    namespace: monitoring
    resourceVersion: "3898"
    uid: 277e358b-591f-44f8-8157-4b9e7aa5f318
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5G
    storageClassName: standard
    volumeMode: Filesystem
    volumeName: pvc-277e358b-591f-44f8-8157-4b9e7aa5f318
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5G
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
