apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-02-21T06:09:31Z"
    name: default
    namespace: monitoring
    resourceVersion: "2625"
    uid: 34c8e2fe-6576-4b14-9011-801d4c8d6c5c
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-02-21T06:09:36Z"
    labels:
      app.kubernetes.io/instance: prometheus
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: grafana
      app.kubernetes.io/version: 9.2.0
      helm.sh/chart: grafana-7.3.0
    name: prometheus-grafana
    namespace: monitoring
    resourceVersion: "2755"
    uid: a5d994ea-4507-4b90-923e-8f655fa7a578
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      helm.sh/hook: test-success
      helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    creationTimestamp: "2025-02-21T06:10:08Z"
    labels:
      app.kubernetes.io/instance: prometheus
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: grafana
      app.kubernetes.io/version: 9.2.0
      helm.sh/chart: grafana-7.3.0
    name: prometheus-grafana-test
    namespace: monitoring
    resourceVersion: "3286"
    uid: 8b49ee35-2323-4720-a8b8-fa6929e1107c
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      helm.sh/hook: pre-install,pre-upgrade,post-install,post-upgrade
      helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    creationTimestamp: "2025-02-21T06:10:08Z"
    labels:
      app: kube-prometheus-stack-admission
      app.kubernetes.io/component: prometheus-operator-webhook
      app.kubernetes.io/instance: prometheus
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 56.6.2
      chart: kube-prometheus-stack-56.6.2
      heritage: Helm
      release: prometheus
    name: prometheus-k8s-admission
    namespace: monitoring
    resourceVersion: "3287"
    uid: 4d841ecc-4684-4777-8c90-00ad6846781c
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-02-21T06:09:36Z"
    labels:
      app: kube-prometheus-stack-alertmanager
      app.kubernetes.io/component: alertmanager
      app.kubernetes.io/instance: prometheus
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kube-prometheus-stack-alertmanager
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 56.6.2
      chart: kube-prometheus-stack-56.6.2
      heritage: Helm
      release: prometheus
    name: prometheus-k8s-alertmanager
    namespace: monitoring
    resourceVersion: "2758"
    uid: c7902bf5-5a53-43a8-aa6b-dc7b6e04b0d2
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-02-21T06:09:36Z"
    labels:
      app: kube-prometheus-stack-operator
      app.kubernetes.io/component: prometheus-operator
      app.kubernetes.io/instance: prometheus
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 56.6.2
      chart: kube-prometheus-stack-56.6.2
      heritage: Helm
      release: prometheus
    name: prometheus-k8s-operator
    namespace: monitoring
    resourceVersion: "2759"
    uid: b8faf19b-6964-462e-a30d-77b481bdd2d1
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-02-21T06:09:36Z"
    labels:
      app: kube-prometheus-stack-prometheus
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: prometheus
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kube-prometheus-stack-prometheus
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 56.6.2
      chart: kube-prometheus-stack-56.6.2
      heritage: Helm
      release: prometheus
    name: prometheus-k8s-prometheus
    namespace: monitoring
    resourceVersion: "2760"
    uid: 4f6715d9-1ff3-4aa2-ba79-105e7723cb58
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-02-21T06:09:36Z"
    labels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: prometheus
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kube-state-metrics
      app.kubernetes.io/part-of: kube-state-metrics
      app.kubernetes.io/version: 2.10.1
      helm.sh/chart: kube-state-metrics-5.16.0
      release: prometheus
    name: prometheus-kube-state-metrics
    namespace: monitoring
    resourceVersion: "2756"
    uid: 2058fdd5-a4f3-41d6-ac23-774e249788d1
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-02-21T06:09:36Z"
    labels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: prometheus
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: prometheus-node-exporter
      app.kubernetes.io/part-of: prometheus-node-exporter
      app.kubernetes.io/version: 1.7.0
      helm.sh/chart: prometheus-node-exporter-4.26.1
      jobLabel: node-exporter
      release: prometheus
    name: prometheus-prometheus-node-exporter
    namespace: monitoring
    resourceVersion: "2757"
    uid: 4a24357a-a3cd-44c4-a591-d314da9d63ff
kind: List
metadata:
  resourceVersion: ""
