apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-operator
  namespace: opentelemetry-operator
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: opentelemetry-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opentelemetry-operator
    app.kubernetes.io/version: "0.85.0"
    helm.sh/chart: opentelemetry-operator-0.39.1
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: controller-manager
      app.kubernetes.io/name: opentelemetry-operator
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller-manager
        app.kubernetes.io/name: opentelemetry-operator
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      serviceAccountName: opentelemetry-operator
      containers:
      - name: manager
        image: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:v0.85.0
        imagePullPolicy: IfNotPresent
        command:
          - /manager
        args:
          - --metrics-addr=0.0.0.0:8080
          - --enable-leader-election
          - --health-probe-addr=:8081
          - --collector-image=otel/opentelemetry-collector-contrib:0.85.0
        env:
          - name: ENABLE_WEBHOOKS
            value: "false"
        ports:
          - containerPort: 8080
            name: metrics
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
      - name: kube-rbac-proxy
        image: quay.io/brancz/kube-rbac-proxy:v0.14.2
        imagePullPolicy: IfNotPresent
        args:
          - --secure-listen-address=0.0.0.0:8443
          - --upstream=http://127.0.0.1:8080/
          - --logtostderr=true
          - --v=0
        ports:
          - containerPort: 8443
            name: https
            protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 64Mi
      securityContext:
        fsGroup: 65532
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
      terminationGracePeriodSeconds: 10
