apiVersion: v1
kind: List
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: opentelemetry-operator-manager
      labels:
        app.kubernetes.io/component: controller-manager
        app.kubernetes.io/instance: opentelemetry-operator
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: opentelemetry-operator
        app.kubernetes.io/version: "0.85.0"
        helm.sh/chart: opentelemetry-operator-0.39.1
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: opentelemetry-operator-manager
    subjects:
      - kind: ServiceAccount
        name: opentelemetry-operator
        namespace: opentelemetry-operator

  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: opentelemetry-operator-proxy
      labels:
        app.kubernetes.io/component: controller-manager
        app.kubernetes.io/instance: opentelemetry-operator
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: opentelemetry-operator
        app.kubernetes.io/version: "0.85.0"
        helm.sh/chart: opentelemetry-operator-0.39.1
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: opentelemetry-operator-proxy
    subjects:
      - kind: ServiceAccount
        name: opentelemetry-operator
        namespace: opentelemetry-operator
