apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: opentelemetry-operator
      namespace: opentelemetry-operator
      labels:
        app.kubernetes.io/component: controller-manager
        app.kubernetes.io/instance: opentelemetry-operator
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: opentelemetry-operator
        app.kubernetes.io/version: "0.85.0"
        helm.sh/chart: opentelemetry-operator-0.39.1

  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: otel-collector
      namespace: opentelemetry-operator
      labels:
        app.kubernetes.io/component: opentelemetry-collector
        app.kubernetes.io/instance: opentelemetry-operator.otel
        app.kubernetes.io/managed-by: opentelemetry-operator
        app.kubernetes.io/name: otel-collector
        app.kubernetes.io/part-of: opentelemetry
        app.kubernetes.io/version: "0.60.0"