apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: opentelemetry-operator
      namespace: opentelemetry-operator
      labels:
        app.kubernetes.io/component: controller-manager
        app.kubernetes.io/instance: opentelemetry-operator
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: opentelemetry-operator
        app.kubernetes.io/version: "0.85.0"
        helm.sh/chart: opentelemetry-operator-0.39.1
    spec:
      type: ClusterIP
      ports:
        - name: https
          port: 8443
          protocol: TCP
          targetPort: https
        - name: metrics
          port: 8080
          protocol: TCP
          targetPort: metrics
      selector:
        app.kubernetes.io/component: controller-manager
        app.kubernetes.io/name: opentelemetry-operator
      sessionAffinity: None

  - apiVersion: v1
    kind: Service
    metadata:
      name: otel-collector
      namespace: opentelemetry-operator
      labels:
        app.kubernetes.io/component: opentelemetry-collector
        app.kubernetes.io/instance: opentelemetry-operator.otel
        app.kubernetes.io/managed-by: opentelemetry-operator
        app.kubernetes.io/name: otel-collector
        app.kubernetes.io/part-of: opentelemetry
        app.kubernetes.io/version: "0.60.0"
    spec:
      type: ClusterIP
      ports:
        - name: jaeger-grpc
          port: 14250
          protocol: TCP
          targetPort: 14250
        - name: otlp-grpc
          port: 4317
          protocol: TCP
          targetPort: 4317
        - name: otlp-http
          port: 4318
          protocol: TCP
          targetPort: 4318
        - name: port-14268
          port: 14268
          protocol: TCP
          targetPort: 14268
        - name: port-6831
          port: 6831
          protocol: UDP
          targetPort: 6831
      selector:
        app.kubernetes.io/component: opentelemetry-collector
        app.kubernetes.io/instance: opentelemetry-operator.otel
        app.kubernetes.io/managed-by: opentelemetry-operator
        app.kubernetes.io/part-of: opentelemetry
      sessionAffinity: None

  - apiVersion: v1
    kind: Service
    metadata:
      name: otel-collector-headless
      namespace: opentelemetry-operator
      labels:
        app.kubernetes.io/component: opentelemetry-collector
        app.kubernetes.io/instance: opentelemetry-operator.otel
        app.kubernetes.io/managed-by: opentelemetry-operator
        app.kubernetes.io/name: otel-collector
        app.kubernetes.io/part-of: opentelemetry
        app.kubernetes.io/version: "0.60.0"
        operator.opentelemetry.io/collector-headless-service: "Exists"
    spec:
      # Headless service
      clusterIP: None
      type: ClusterIP
      ports:
        - name: jaeger-grpc
          port: 14250
          protocol: TCP
          targetPort: 14250
        - name: otlp-grpc
          port: 4317
          protocol: TCP
          targetPort: 4317
        - name: otlp-http
          port: 4318
          protocol: TCP
          targetPort: 4318
        - name: port-14268
          port: 14268
          protocol: TCP
          targetPort: 14268
        - name: port-6831
          port: 6831
          protocol: UDP
          targetPort: 6831
      selector:
        app.kubernetes.io/component: opentelemetry-collector
        app.kubernetes.io/instance: opentelemetry-operator.otel
        app.kubernetes.io/managed-by: opentelemetry-operator
        app.kubernetes.io/part-of: opentelemetry
      sessionAffinity: None

  - apiVersion: v1
    kind: Service
    metadata:
      name: otel-collector-monitoring
      namespace: opentelemetry-operator
      labels:
        app.kubernetes.io/component: opentelemetry-collector
        app.kubernetes.io/instance: opentelemetry-operator.otel
        app.kubernetes.io/managed-by: opentelemetry-operator
        app.kubernetes.io/name: otel-collector-monitoring
        app.kubernetes.io/part-of: opentelemetry
        app.kubernetes.io/version: "0.60.0"
    spec:
      type: ClusterIP
      ports:
        - name: monitoring
          port: 8888
          protocol: TCP
          targetPort: 8888
      selector:
        app.kubernetes.io/component: opentelemetry-collector
        app.kubernetes.io/instance: opentelemetry-operator.otel
        app.kubernetes.io/managed-by: opentelemetry-operator
        app.kubernetes.io/part-of: opentelemetry
      sessionAffinity: None
