apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector
  namespace: opentelemetry-operator
  labels:
    app.kubernetes.io/component: opentelemetry-collector
    app.kubernetes.io/instance: opentelemetry-operator.otel
    app.kubernetes.io/managed-by: opentelemetry-operator
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: opentelemetry
    app.kubernetes.io/version: "0.60.0"
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8888"
    prometheus.io/scrape: "true"
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: opentelemetry-collector
      app.kubernetes.io/instance: opentelemetry-operator.otel
      app.kubernetes.io/managed-by: opentelemetry-operator
      app.kubernetes.io/part-of: opentelemetry
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: opentelemetry-collector
        app.kubernetes.io/instance: opentelemetry-operator.otel
        app.kubernetes.io/managed-by: opentelemetry-operator
        app.kubernetes.io/name: otel-collector
        app.kubernetes.io/part-of: opentelemetry
        app.kubernetes.io/version: "0.60.0"
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8888"
        prometheus.io/scrape: "true"
    spec:
      hostNetwork: true
      serviceAccountName: otel-collector
      containers:
      - name: otc-container
        image: otel/opentelemetry-collector-contrib:0.60.0
        imagePullPolicy: IfNotPresent
        args:
          - --config=/conf/collector.yaml
        ports:
          - containerPort: 14250
            name: jaeger-grpc
            protocol: TCP
          - containerPort: 8888
            name: metrics
            protocol: TCP
          - containerPort: 4317
            name: otlp-grpc
            protocol: TCP
          - containerPort: 4318
            name: otlp-http
            protocol: TCP
          - containerPort: 14268
            name: port-14268
            protocol: TCP
          - containerPort: 6831
            name: port-6831
            protocol: UDP
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
          - name: otc-internal
            mountPath: /conf
      volumes:
        - name: otc-internal
          configMap:
            name: otel-collector
            items:
              - key: collector.yaml
                path: collector.yaml
