apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tempo
  namespace: tempo
  labels:
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tempo
    app.kubernetes.io/version: "2.2.2"
    helm.sh/chart: tempo-1.6.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: tempo
      app.kubernetes.io/name: tempo
  serviceName: tempo-headless
  podManagementPolicy: OrderedReady
  revisionHistoryLimit: 10
  updateStrategy:
    type: RollingUpdate
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: tempo
        app.kubernetes.io/name: tempo
      annotations:
        checksum/config: bd6e8c69e8b055e5473f7a6e4db7af4cdf8b0d2f735f014660fce63b0ce98cb3
    spec:
      serviceAccountName: tempo
      automountServiceAccountToken: true
      containers:
      - name: tempo
        image: grafana/tempo:2.2.2
        imagePullPolicy: IfNotPresent
        args:
          - -config.file=/conf/tempo.yaml
          - -mem-ballast-size-mbs=1024
        ports:
          - containerPort: 3100
            name: prom-metrics
            protocol: TCP
          - containerPort: 6831
            name: jaeger-thrift-c
            protocol: UDP
          - containerPort: 6832
            name: jaeger-thrift-b
            protocol: UDP
          - containerPort: 14268
            name: jaeger-thrift-h
            protocol: TCP
          - containerPort: 14250
            name: jaeger-grpc
            protocol: TCP
          - containerPort: 9411
            name: zipkin
            protocol: TCP
          - containerPort: 55680
            name: otlp-legacy
            protocol: TCP
          - containerPort: 4317
            name: otlp-grpc
            protocol: TCP
          - containerPort: 55681
            name: otlp-httplegacy
            protocol: TCP
          - containerPort: 4318
            name: otlp-http
            protocol: TCP
          - containerPort: 55678
            name: opencensus
            protocol: TCP
        volumeMounts:
          - name: tempo-conf
            mountPath: /conf
      volumes:
        - name: tempo-conf
          configMap:
            name: tempo
            defaultMode: 420
